---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create dynamo table with hash and range primary key
      dynamodb_table:
        name: pizza-orders
        region: us-east-2
        hash_key_name: orderId
        hash_key_type: STRING
        read_capacity: 1
        write_capacity: 1
        tags:
          tag_name: pizza-api